### ISSUE TITLE
How did you backdoor it

### ISSUE THREAD

**Issue by Deafult-Profile** [Crystallinqq/PyroClient#16]

**Comment by Markdojo13** [comment]
not backdoored smooth brain monkey

**Comment by Deafult-Profile** [comment]
please I want to know which file..

**Comment by Markdojo13** [comment]
Stupid smooth brain

Its not

**Comment by Deafult-Profile** [comment]
PLEASE

**Comment by Deafult-Profile** [comment]
how do u know it is not backdoored..

**Comment by Markdojo13** [comment]
Because I am smart and know how to check the fucking coding

**Comment by wawddd** [comment]
> Stupid smooth brain
> 
> Its not

lol

**Comment by Markdojo13** [comment]
And wawd told me its not B)

**Comment by Deafult-Profile** [comment]
okay I do not trust you but I trust wawddd

**Comment by Deafult-Profile** [comment]
thank you wawddd

**Comment by Deafult-Profile** [comment]
but what if he was lying

**Comment by Markdojo13** [comment]
he isnt

**Comment by Deafult-Profile** [comment]
I don't believe u.. he is using a token logger!

**Comment by Crystallinqq** [comment]
unfunny troll.
