### ISSUE TITLE
writing $ in chat crash

### ISSUE THREAD

**Issue by ThugPenguin1** [Crystallinqq/PyroClient#21]
it crashes when you write $ 
recomment and ill send the crash log

**Comment by me-rgb** [comment]
Noob

**Comment by ThugPenguin1** [comment]
Eh? No u

**Comment by 25iscool** [comment]
L

**Comment by xiguajerry** [comment]
not full crack

**Comment by supakeks** [comment]
It's a crack, there won't be any bug fixes or whatsoever

**Comment by ThugPenguin1** [comment]
This is actually legit lol, boat fly works

**Comment by Crystallinqq** [comment]
fixed in newest 1.3.1 👍
