### ISSUE TITLE
Nice token logger

### ISSUE THREAD

**Issue by me-rgb** [Crystallinqq/PyroClient#24]
lmao take out the token logger or get reported.

**Comment by ya-ilya** [comment]
no proof no talk

**Comment by me-rgb** [comment]
Got proof

**Comment by me-rgb** [comment]
![logger](https://user-images.githubusercontent.com/56459146/96007138-3403e900-0e0c-11eb-9c3e-6f4d5d668bf9.PNG)

**Comment by ya-ilya** [comment]
this is rofl

**Comment by me-rgb** [comment]
Hm?

**Comment by me-rgb** [comment]
Want a screenshot of the entire page?

**Comment by Pharmacies** [comment]
its a running joke thats been going on forever

**Comment by MysteriousYter** [comment]
nah its not

**Comment by MysteriousYter** [comment]
> Want a screenshot of the entire page?

can you i would like to see

**Comment by Pharmacies** [comment]
nobody has proof other than people spamming the message in discords which we've been doing as a joke ever since future crack

**Comment by MysteriousYter** [comment]
> nobody has proof other than people spamming the message in discords which we've been doing as a joke ever since future crack

hmm true idk tho

**Comment by me-rgb** [comment]
![heregithub](https://user-images.githubusercontent.com/56459146/96028944-f6ad5480-0e27-11eb-8ca5-4a94de65bd5a.PNG)
here

**Comment by ilan1009** [comment]
Its literally a joke
Dumbass.

**Comment by kylerittenhause** [comment]
> ![heregithub](https://user-images.githubusercontent.com/56459146/96028944-f6ad5480-0e27-11eb-8ca5-4a94de65bd5a.PNG)
> here

its a joke

**Comment by Lqnz** [comment]
Monkey

**Comment by Oecher1** [comment]
> ![heregithub](https://user-images.githubusercontent.com/56459146/96028944-f6ad5480-0e27-11eb-8ca5-4a94de65bd5a.PNG)
> here

are you trolling or are you that dumb

**Comment by Crystallinqq** [comment]
niggas out here really this retarded :joy:

**Comment by Lqnz** [comment]
> niggas out here really this retarded :joy:

Indeed

**Comment by MysteriousYter** [comment]
> niggas out here really this retarded 😂

/shurg

**Comment by l1ving** [comment]
holy shit this is top tier #cringe-compilation

**Comment by MysteriousYter** [comment]
> holy shit this is top tier #cringe-compilation

it is but who are you

**Comment by l1ving** [comment]
> Opened their first issue on GitHub in Crystallinqq/PyroClient Oct 14

Should you be asking me that?

**Comment by MysteriousYter** [comment]
> > Opened their first issue on GitHub in Crystallinqq/PyroClient Oct 14
> 
> Should you be asking me that?

i can and i have

**Comment by l1ving** [comment]
# :moyai:

**Comment by ilan1009** [comment]
indeed
