### ISSUE TITLE
binds don't work

### ISSUE THREAD

**Issue by Arctozolt** [Crystallinqq/PyroClient#3]
click gui is permanently \ lol u can't bind to anything else

**Comment by SpicyBigGithub** [comment]
idc

**Comment by Crystallinqq** [comment]
pyro issue not crack issue

**Comment by Crystallinqq** [comment]
try binding thru command. prefix is $

**Comment by Arctozolt** [comment]
nup tried doing $bind clickgui p and it was still stuck on \
